changelog:
  categories:
    - title: 🚀 기능 추가 및 기능변경
      labels:
        - feat
        - feature
        - change
    - title: 🐞 오류 해결
      labels:
        - fix
        - hotfix
    - title: ⚙️ 성능 및 구조 개선
      labels:
        - refactor
        - perf
  exclude:
    labels:
      - docs
      - chore
      - ci
      - test
      - build
      - style
