changelog:
  categories:
    - title: 🚀 기능 추가 및 기능변경
      labels:
        - feature
        - change
    - title: 🐞 오류 해결
      labels:
        - bug
    - title: ⚙️ 성능 및 구조 개선
      labels:
        - enhancement
        - refactor
    - title: Others

  exclude:
    labels:
      - documentation
      - chore
