name: New Feature
description: 새 기능 개발/변경 혹은 기능개선
title: '[FEAT] '
labels: ['feature']
body:
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: 구현할 기능에 대한 상세 설명을 적어주세요.
      placeholder: '예: 사용자 프로필에 닉네임 변경 기능 추가'
    validations:
      required: true
  - type: textarea
    id: feature-list
    attributes:
      label: ✨ Feature
      description: 개발할 세부 기능 목록을 적어주세요.
      value: |
        - [ ] todo 1
        - [ ] todo 2
  - type: textarea
    id: etc
    attributes:
      label: ETC
      description: 기타사항을 적어주세요.
